### ISSUE TITLE
Suggestion to avoid hard-coding server IPs

### ISSUE THREAD

**Issue by Chopper1337** [FN-FAL113/csgo-server-picker#5]
You currently hard code the servers and their IPs which isn't ideal as you'd need to keep this application updated whenever Valve change those IPs.

You could instead use https://api.steampowered.com/ISteamApps/GetSDRConfig/v1?appid=730 and parse the response to get the server list from Valve directly.

I would create a PR for this but I don't know VB.

**Comment by FN-FAL113** [comment]
> You currently hard code the servers and their IPs which isn't ideal as you'd need to keep this application updated whenever Valve change those IPs.
> 
> You could instead use https://api.steampowered.com/ISteamApps/GetSDRConfig/v1?appid=730 and parse the response to get the server list from Valve directly.
> 
> I would create a PR for this but I don't know VB.

its part of the todo below the readme of this project, I'm currently reviewing how valve update their server ip's if they only do update the host range then it will be fine else I should fetch the data

**Comment by FN-FAL113** [comment]
Pr's are welcome but not forced :D but for now if they update the whole ip I should implement fetching data

**Comment by FN-FAL113** [comment]
Just want to update, this one is on progress now :D
